import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
// import Footer from "@/components/footer";
import { headers } from 'next/headers';
import AnnouncementBanner from "@/components/announcement-banner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const headersList = headers();
  const hideNav = headersList.get('x-hide-nav') === 'true';

  return (
    <html lang="en">
      <body className="min-h-screen bg-white">
        {!hideNav && (
          <>
            <AnnouncementBanner />
            <Navbar />
          </>
        )}
        <main className="relative">{children}</main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
